name: dissertation_project_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0
# sdk: '>=3.4.3 <4.0.0'
environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  meta: ^1.10.0
  bloc_concurrency: ^0.2.2
  http: ^1.2.1
  equatable: ^2.0.5
  uuid: ^4.5.1
  connectivity_plus: ^6.0.5
  flutter_gen: ^5.7.0
  intl: ^0.19.0

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.4
  mocktail: ^1.0.0

flutter_gen:
  localizations:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  untranslated-messages-file: untranslated_messages.txt

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/images/star.png
