name: dissertation_project_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0
# sdk: '>=3.4.3 <4.0.0'
environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  meta: ^1.10.0
  bloc_concurrency: ^0.2.2
  http: ^1.2.1
  equatable: ^2.0.5
  uuid: ^4.5.1
  connectivity_plus: ^6.0.5
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  permission_handler: ^11.1.0
  hive_flutter: ^1.1.0
  hive: ^2.0.0

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.4
  mocktail: ^1.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/images/star.png
    - assets/images/earth.png
    - assets/images/space2.jpeg
